# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f28ad68200f1c2bd93f5b38a29460913928c5c10ceeac9b232b10ee268b03a5cac9d50fb77f54520cbabff1a9b06eba457119c4e7f24a38055508c797435638c

test:
  secret_key_base: 24dea3ac696bebe3a8396cc5676285c6c7c21a8dfc7d9e2862274a21c5b200103af9946798fdda77163602d7ef8c1741ad37096c386c1a7b161f68f0d89ad95c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
