# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2033aad097ebf0287e40d3dc973b509c673b206bf9835ecb991c007a062d40afbfdc2ece4a4c021858c8a330e718265ac4b4ebc5ae4d0bba4368cb8aae7d34f

test:
  secret_key_base: 8ecdd119fa5044c4154d4411f30c069f14a511bd697a2cfecb918e75527a8b301684e5791c06b47e9aa88be3d1e9aeb167d6fec31c348e9f122cddb008f22cb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
